<!--feed editor pop up modal-->
<?php $default = user_privacy("feed-editor-privacy", 1); $privacy = (isset($privacy)) ? $privacy : $default; $avatar = (isset($avatar)) ? $avatar : get_avatar(75); ?>
<div id="editorModal" class="modal fade hidden-sm-down " tabindex="-1" role="dialog" aria-labelledby="confirmModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-md">
        <div class="modal-content" id="feed-editor">
            <div class="modal-header">
                <span><i class="ion-edit"></i><?php echo lang('feed::create-post'); ?> </span>
                <span id="editorClose" href="#" class="pull-right">X</span>
            </div>
            <div id="post-editor-indicator">
                <img src="<?php echo img('images/loading.gif') ?>"/> <span id="feed-media-upload-indicator">0%</span>
            </div>
            <form style="margin: 0;padding: 0" id="feed-editor-form" action="" method="post">
                <?php CSRFProtection::embed() ?>
                <input type="hidden" name="val[privacy]" value="<?php echo $privacy ?>" id="feed-editor-privacy"/>
                <input type="hidden" name="val[type]" value="<?php echo (isset($type)) ? $type : 'feed' ?>"/>
                <input type="hidden" name="val[type_id]" value="<?php echo (isset($type_id)) ? $type_id : '' ?>"/>
                <input type="hidden" name="val[type_data]" value="<?php echo (isset($type_data)) ? $type_data : '' ?>"/>
                <input type="hidden" name="val[entity_id]" value="<?php echo (isset($entity_id)) ? $entity_id : get_userid() ?>"/>
                <input type="hidden" name="val[entity_type]" value="<?php echo (isset($entity_type)) ? $entity_type : 'user' ?>"/>
                <input type="hidden" name="val[to_user_id]" value="<?php echo (isset($to_user_id)) ? $to_user_id : null ?>"/>
                <input type="hidden" name="val[background]" value="<?php echo (isset($background)) ? $background : null ?>" class="feed-editor-background-input">
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-2">
                            <a ajax="true" href="<?php echo profile_url() ?>" class="avatar"><img class="feed-avatar" src="<?php echo $avatar ?>"/>
                            </a>
                        </div>
                        <div class="col-md-10">
                            <div id="feed-editor-content-container">
                                <div id="feed-editor-content">
                                    <textarea id="editorModal-feed-editor-textarea" class="transparent" data-height="40px" data-mention="#feed-editor-mention" class="auto-grow-input mention-input <?php echo (config('enable-feed-text-limit', false)) ? 'textarea-limit' : null ?>" data-text-limit="<?php echo config('maximum-feed-text-limit', 150) ?>" data-text-limit-count-target="#feed-editor-text-limit" name="val[content]" placeholder="<?php echo lang('feed::whats-happening') ?>"></textarea>
                                    <div class="feed-editor-background" style="display: none">
                                        <textarea id="editorModal-feed-editor-textarea-bg" class="auto-grow-input mention-input <?php echo (config('enable-feed-text-limit', false)) ? 'textarea-limit' : null ?>" data-text-limit="<?php echo config('maximum-feed-text-limit', 150) ?>" data-text-limit-count-target="#feed-editor-text-limit" placeholder="<?php echo lang('feed::whats-happening') ?>" style="background:none;text-align:center; "></textarea>
                                    </div>
                                    <div class="feed-bg-container">
                                        <table cols="9" cellspacing="0" cellpadding="0" class="feed-editor-colors" style="display:none">
                                            <tbody>
                                                <tr>
                                                    <td>
                                                        <div class="colorbox">
                                                            <a href="#" onclick="return feedEditor.toggleBackground('open', 'default')">
                                                                <div class="colorcircle"></div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                    <td>
                                                        <div class="colorbox">
                                                            <a href="#" onclick="return feedEditor.toggleBackground('open', 'color1')">
                                                                <div class="colorcircle" style="background-color: rgb(252, 216, 114);"></div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                    <td>
                                                        <div class="colorbox">
                                                            <a href="#" onclick="return feedEditor.toggleBackground('open', 'color2')">
                                                                <div class="colorcircle" style="background-color: rgb(243, 83, 105);"></div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                    <td>
                                                        <div class="colorbox">
                                                            <a href="#" onclick="return feedEditor.toggleBackground('open', 'color3')">
                                                                <div class="colorcircle" style="background-color: rgb(243, 83, 105);"></div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                    <td>
                                                        <div class="colorbox">
                                                            <a href="#" onclick="return feedEditor.toggleBackground('open', 'color4')">
                                                                <div class="colorcircle" style="background-color: rgb(23, 172, 255);"></div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                    <td>
                                                        <div class="colorbox">
                                                            <a href="#" onclick="return feedEditor.toggleBackground('open', 'color5')">
                                                                <div class="colorcircle" style="background-color: rgb(74, 144, 226);"></div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                    <td>
                                                        <div class="colorbox">
                                                            <a href="#" onclick="return feedEditor.toggleBackground('open', 'color6')">
                                                                <div class="colorcircle" style="background-color: rgb(93, 63, 218);"></div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                    <td>
                                                        <div class="colorbox">
                                                            <a href="#" onclick="return feedEditor.toggleBackground('open', 'color7')">
                                                                <div class="colorcircle" style="background-color: rgb(95, 102, 115);"></div>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                    <div id="feed-editor-activity-container"></div>
                                    <div id="feed-editor-link-container">
                                        <div class="link-indicator">
                                            <img src="<?php echo img('images/loading.gif') ?>"/>
                                            <?php echo lang('feed::retrieving-link-details') ?>
                                        </div>
                                        <div class="link-content"></div>
                                    </div>
                                    <div id="feed-editor-mention" class="mention-user-list box">
                                        <img src="<?php echo img('images/loading.gif') ?>" class="indicator"/>
                                        <div class="listing user-suggestion-list"></div>
                                    </div>
                                    <div class="" id="feed-editor-check-in-input-container">
                                        <i class="ion-android-pin"></i>
                                        <input id="feed-geocomplete" autocomplete="off" type="text" name="val[location]" placeholder="<?php echo lang('where-are-you') ?>"/>
                                        <a href="" onclick="return feedEditor.removeCheckIn()"><i class="ion-close"></i></a>
                                    </div>
                                    <div id="photo-feed-media-selected-info" class="feed-media-selected-info">
                                        <i class="ion-camera"></i>
                                        <span class="count">0</span> <?php echo lang('photos-selected') ?>
                                        <a class="remove" onclick="return feedEditor.removeImage()" href=""><i class="ion-close"></i></a>
                                    </div>
                                    <div id="video-feed-media-selected-info" class="feed-media-selected-info">
                                        <i class="ion-ios-videocam"></i>
                                        <span class="count">0</span> <?php echo lang('video-selected') ?>
                                        <a class="remove" onclick="return feedEditor.removeVideo()" href=""><i class="ion-close"></i></a>
                                    </div>
                                    <div id="file-feed-media-selected-info" class="feed-media-selected-info">
                                        <i class="ion-document-text"></i>
                                        <span class="count">0</span> <?php echo lang('files-selected') ?>
                                        <a class="remove" onclick="return feedEditor.removeFile()" href=""><i class="ion-close"></i></a>
                                    </div>
                                    <div id="feed-editor-tags-container">
                                        <span style="display: none" class="" id="user-<?php echo get_userid() ?>"> </span>
                                        <span class="input-field">
                                            <input data-friend-only="true" autocomplete="off" data-target="#feed-tags-suggestion" type="text" class="user-tag-input" placeholder="<?php echo lang('tag-people-in-post') ?>"/>
                                            <div class="user-suggestion-list box" id="feed-tags-suggestion"></div>
                                        </span>
                                    </div>
                                    <div class="feed-editor-feeling-container dropdown clearfix">
                                        <div class="feeling-left">
                                            <?php $feelings = get_feelings_list(); $firstFeeling = $feelings[0]; ?>
                                            <a id="dropdown-link" href="" data-toggle="dropdown"><img src="<?php echo img("images/status/{$firstFeeling}.png") ?>"/><?php echo lang("feed::{$firstFeeling}") ?></a>
                                            <ul class="dropdown-menu">
                                                <?php foreach ($feelings as $feeling): ?>
                                                <li><a onclick="return feedEditor.loadFeeling(this)" href="" data-type="<?php echo $feeling ?>" class="dropdown-item"><img src="<?php echo img("images/status/{$feeling}.png") ?>"/> <?php echo lang("feed::{$feeling}") ?><i class="ion-chevron-right pull-right"></i></a></li>
                                                <?php endforeach ?>
                                            </ul>
                                        </div>
                                        <div class="feeling-right">
                                            <input type="hidden" name="val[feeling_type]" id="feed-editor-feeling-type" value="<?php echo $firstFeeling ?>">
                                            <input type="hidden" name="val[feeling_data]" id="feed-editor-feeling-data" value="">
                                            <input type="text" autocomplete="off" name="val[feeling_text]" onblur="return feedEditor.removeFeeling(this)" onkeyup="return feedEditor.listenMediaFeeling(this)" id="feed-editor-feeling-text"/>
                                            <div id="feed-feeling-selected-suggestion"></div>
                                            <div id="feed-feeling-suggestion"></div>
                                        </div>
                                    </div>
                                    <div class="feed-editor-poll-container">
                                        <input type="hidden" value="0" name="val[poll]" id="feed-poll-enable-input"/>
                                        <div class="poll-options-container">
                                            <div class="options">
                                                <i class="ion-ios-plus-outline"></i>
                                                <input placeholder="<?php echo lang('feed::option') ?>" type="text" name="val[poll_options][]"/>
                                            </div>
                                            <div class="options">
                                                <i class="ion-ios-plus-outline"></i>
                                                <input placeholder="<?php echo lang('feed::option') ?>" type="text" name="val[poll_options][]"/>
                                            </div>
                                        </div>
                                        <a style="display:inline-block;" href="" onclick="return feedEditor.addOptions()"><i class="ion-ios-plus"></i> <?php echo lang('feed::add-option') ?></a>
                                        <span class="">
                                            <label class="c-input c-checkbox">
                                                <input name="val[poll_multiple]" type="checkbox">
                                                <span class="c-indicator"></span>
                                                <?php echo lang('feed::enable-multiple-section') ?>
                                                </label>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <hr class="light-separate" />
                    <div class="row">
                        <div class="col-md-12 center-col">
                            <div class="col-md-4">
                                <ul class="editor-action">
                                    <?php if (user_has_permission('can-upload-photo-feed')): ?>
                                    <li>
                                        <span class="file-input"><input accept="image/*" multiple="" onchange="feedEditor.processMedia('image')" type="file" id="editorModal-feed-editor-image-input" name="image[]"></span>
                                        <a id="feed-editor-image-selector" href="" onclick="return feedEditor.choose('#editorModal-feed-editor-image-input', 'image')"><i class="ion-camera green"></i><span>Photo</span></a>
                                    </li>
                                    <?php endif ?>
                                    <li id="feed-editor-check-in-input-selector">
                                        <a onclick="return feedEditor.toggleCheckIn()" title="" href=""><i class="ion-ios-location red"></i>Check in</a>
                                    </li>
                                    <?php fire_hook('feed.editor.modal.actions',null, array('column' => 1)); ?>
                                </ul>
                            </div>
                            <div class="col-md-4">
                                <ul class="editor-action">
                                    <?php if (user_has_permission('can-upload-video-feed')): ?>
                                    <li>
                                        <span class="file-input"><input <?php echo (plugin_loaded('video') and config('video-upload', false) and config('video-encoder') != 'none') ? '' : 'accept="video/mp4"' ?> onchange="feedEditor.processMedia('video')" type="file" id="editorModal-feed-editor-video-input" name="video"/></span>
                                        <a id="feed-editor-video-selector" href="" onclick="return feedEditor.choose('#editorModal-feed-editor-video-input', 'video')"><i class="ion-ios-videocam blue"></i><span>Video</span></a>
                                    </li>
                                    <?php endif ?>
                                    <?php if (config('enable-feed-poll', true) and user_has_permission('can-create-poll')): ?>
                                        <li><a id="feed-editor-poll-toggle" data-revert="What is on your mind?" data-holder="Ask question.." onclick="return feedEditor.openPoll(this)" href="" class=""><i class="ion-stats-bars purple"></i>Create Poll</a></li>
                                    <?php endif ?>
                                    <?php if (user_has_permission('can-use-feeling')): ?>
                                        <li><a class="feed-feeling-trigger" href="" title=""><i class="ion-android-happy blue"></i><span><?php echo lang('feed::feelings') ?></span></a></li>
                                    <?php endif ?>
                                    <?php fire_hook('feed.editor.modal.actions',null, array('column' => 2)); ?>
                                </ul>
                            </div>
                            <div class="col-md-4">
                                <ul class="editor-action">
                                    <?php if (user_has_permission('can-share-file-feed')): ?>
                                        <li>
                                            <span class="file-input"><input onchange="feedEditor.processMedia('file')" multiple type="file" id="editorModal-feed-editor-file-input" name="file[]"/></span>
                                            <a onclick="return feedEditor.choose('#editorModal-feed-editor-file-input', 'file')" href=""><i class="ion-android-cloud-outline gold"></i><span><?php echo lang('feed::file') ?></span></a>
                                        </li>
                                    <?php endif ?>
                                    <li>
                                        <div>
                                            <div class="emoticon-box  pull-right" style="right: 0; top:20px"></div>
                                            <a data-target="editorModal-feed-editor-textarea" data-action="0" title="<?php echo lang('emoticons::add-emoticon') ?>" class="emoticon-button" href="javascript::void(0)"><i class="ion-happy-outline emo-button magenta"></i><span><?php echo lang('emoticons::emoticons') ?></span></a>
                                        </div>
                                    </li>
                                    <li><a class="feed-background-trigger" onclick=" return feedEditor.toggleBackground()" href="" title=""><i class="ion-ios-color-wand-outline yellow"></i><?php echo lang('feed::background') ?></a></li>
                                    <?php fire_hook('feed.editor.modal.actions',null, array('column' => 3)); ?>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="right-buttons pull-right">
                        <?php if (config('enable-feed-text-limit', false)): ?>
                        <span id="feed-editor-text-limit"><?php echo config('maximum-feed-text-limit', 150) ?></span>
                        <?php endif ?>
                        <div class=" dropdown" style="display: inline-block">
                            <?php if (!isset($offPrivacy) or (isset($offPrivacy) and !$offPrivacy)): ?>
                            <a id="feed-editor-privacy-toggle" href="" class="dropdown-toggle btn btn-secondary btn-sm" data-toggle="dropdown">
                                <?php $editorPrivacy = user_privacy("feed-editor-privacy", config('default-feed-privacy', 1)); ?>
                                <?php if ($editorPrivacy == 1): ?>
                                <i class="ion-earth" data-toggle="tooltip" title="<?php echo lang('public') ?>"></i></span>
                                <?php elseif ($editorPrivacy == 2): ?>
                                <i class="ion-ios-people" data-toggle="tooltip" title="<?php echo (config('relationship-method', 3) == 1) ? lang('feed::followers-only') : lang('feed::friends-only') ?>"></i>
                                <?php else: ?>
                                <i class="ion-android-lock" data-toggle="tooltip" title="<?php echo lang('feed::only-me') ?>"></i>
                                <?php endif ?>
                            </a>
                            <?php if(!isset($app->profilePage) && !isset($app->profileGroup)):?>
                            <ul id='feed-privacy-dropdown' class='dropdown-menu dropdown-menu-right'>
                                <li><a data-id="1" class="dropdown-item" href="javascript:void(0)"><i class="ion-android-globe"></i><span><?php echo lang('public') ?></span></a></li>
                                <li><a data-id="2" class="dropdown-item" href="javascript:void(0)"><i class="ion-ios-people"></i><span><?php echo (config('relationship-method', 3) == 1) ? lang('feed::followers-only') : lang('feed::friends-only') ?></span></a></li>
                                <li><a data-id="3" class="dropdown-item" href="javascript:void(0)"><i class="ion-android-lock"></i><span><?php echo lang('feed::only-me') ?></span> </a></li>
                            </ul>
                        <?php endif;?>
                            <?php endif; ?>
                        </div>
                        <button class="btn btn-post btn-sm"> <?php echo lang('post') ?></button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>