<div class="wrapper">
    <div class="wrapper-title">
        <?php _lang('verification-requests')?>

    </div>
    <div class="wrapper-content">

        <table class="table table-bordered" style="margin-top: 20px">
            <thead>
            <tr>
                <th style="width: 10%">ID</th>
                <th style="width: 25%"><?php _lang('entity')?></th>
                <th style="width: 15%"><?php _lang('type')?></th>
                <th style="width: 15%"><?php _lang('time')?></th>
                <th style="width: 24%; text-align:center;"><?php _lang('actions')?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach($requests->results() as $request):?>
                <tr>
                    <td><?php echo $request['type_id']?></td>
                    <td>
                        <?php if($request['type'] == 'user'): $user = find_user($request['type_id']) ?>
                            <a href="<?php echo profile_url(null, $user)?>">
                                <img src="<?php echo get_avatar(75, $user)?>" width="30" height="30"/>
                                <h6><?php echo get_user_name($user)?></h6>
                            </a>
                        <?php else: $page = find_page($request['type_id'])?>
                            <a href="<?php echo page_url(null, $page)?>">
                                <img src="<?php echo get_page_logo(75, $page)?>" width="30" height="30"/>
                                <h6><?php echo $page['page_title']?></h6>
                            </a>
                        <?php endif?>
                    </td>
                    <td><?php echo ucwords($request['type'])?></td>
                    <td><?php echo date('d F Y g:i', $request['time'])?></td>
                    <td>
                       <?php if(!$request['ignored']):?>
                           <a href="#" data-toggle="modal" data-target="#myModal-<?php echo $request['type']?>-<?php echo $request['type_id']?>" class="offer-img btn btn-sm btn-warning"><?php _lang('view')?></a>

                           <a href="<?php echo url('admincp/verify/action?type=ignore&id='.$request['id'])?>" class="btn btn-sm btn-danger"><?php _lang('ignore')?></a>

                           <a href="<?php echo  url('admincp/verify/action?type=approve&id='.$request['id'])?>" class="btn btn-sm btn-success"><?php _lang('approve')?></a>
                        <?php endif?>
                    </td>
                </tr>




            <?php endforeach?>
            </tbody>
        </table>

        <?php foreach($requests->results() as $request):?>
            <?php  $request_answers = get_verification_answers($request['id']) ?>
            <?php if($request['type'] == 'user'):?>
            <?php  $user = find_user($request['type_id']) ?>
            <?php else: ?>
            <?php  $page = find_page($request['type_id']) ?>
            <?php endif?>



        <?php if($request['type'] == 'user'):?>
        <div class="modal fade" id="myModal-<?php echo $request['type']?>-<?php echo $request['type_id']?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content modal-info">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    </div>
                    <div class="modal-body">

                        <!----User details---->

                        <div class="info widget-shadow info-box">
                            <div class="info-title">
                                <h4><?php echo get_user_name($user)?> </h4>
                            </div>
                            <div class="info-body dash">

                                <center><img src="<?php echo get_avatar(75, $user)?>" width="150px" height="100px" />	</center>


                                <table width="90%" height="180" style="margin:auto; max-height:130px; text-align:left">
                                    <?php foreach($request_answers as $answer):?>
                                    <tr>
                                        <td class="bold"><?php echo $answer ['question'] ?></td>
                                        <?php if($answer['input_type'] == 'text' || $answer['input_type'] == 'boolean'):?>
                                            <td class="italic"><?php echo $answer ['answer'] ?> </td>
                                            <?php elseif($answer['input_type'] == 'file'):?>
                                        <td class="italic"><a href="<?php echo url($answer['answer']) ?>"  download ><i style="font-size: 22px;" class="ion-ios-cloud-download-outline"></i></a></td>
                                            <?php endif ?>
                                    </tr>
                                    <?php endforeach ?>

                                </table>

                                <div class="clear"></div>
                                <table class="button_table">
                                    <tr>
                                       <td align="center">
                                            <a href="<?php echo url('admincp/verify/action?type=ignore&id='.$user['id'])?>"><button type="button" class="btn btn-sm btn-danger"><?php _lang('ignore')?></button></a>
                                        </td>

                                        <td align="center">
                                            <a href="<?php echo  url('admincp/verify/action?type=approve&id='.$user['id'])?>"><button type="button" class="btn btn-sm btn-success"><?php _lang('approve')?></button></a>
                                        </td>
                                    </tr>
                                </table>

                                <div class="clear"></div>
                            </div>
                        </div>


                        
                    </div>
                </div>
            </div>
        </div>


        <?php elseif($request['type'] == 'page'):?>


                <div class="modal fade" id="myModal-<?php echo $request['type']?>-<?php echo $request['type_id']?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content modal-info">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            </div>
                            <div class="modal-body">

                                <!----User details---->

                                <div class="info widget-shadow info-box">
                                    <div class="info-title">
                                        <h4><?php echo $page['page_title']?></h4>
                                    </div>
                                    <div class="info-body dash">

                                        <center><img src="<?php echo get_page_logo(75, $page)?>" width="150px" height="100px" />	</center>


                                        <table width="90%" height="180" style="margin:auto; max-height:130px; text-align:left">
                                            <?php foreach($request_answers as $answer):?>
                                                <tr>
                                                    <td class="bold"><?php echo $answer ['question'] ?></td>
                                                    <?php if($answer['input_type'] == 'text' || $answer['input_type'] == 'boolean'):?>
                                                        <td class="italic"><?php echo $answer ['answer'] ?> </td>
                                                    <?php elseif($answer['input_type'] == 'file'):?>
                                                        <td class="italic"><a href="<?php echo url($answer['answer']) ?>"  download ><i style="font-size: 22px;" class="ion-ios-cloud-download-outline"></i></a></td>
                                                    <?php endif ?>
                                                </tr>
                                            <?php endforeach ?>

                                        </table>

                                        <div class="clear"></div>
                                        <table class="button_table">
                                            <tr>
                                                <td align="center">
                                                    <a href="<?php echo url('admincp/verify/action?type=ignore&id='.$user['id'])?>"><button type="button" class="btn btn-sm btn-danger"><?php _lang('ignore')?></button></a>
                                                </td>

                                                <td align="center">
                                                    <a href="<?php echo  url('admincp/verify/action?type=approve&id='.$user['id'])?>"><button type="button" class="btn btn-sm btn-success"><?php _lang('approve')?></button></a>
                                                </td>
                                            </tr>
                                        </table>

                                        <div class="clear"></div>
                                    </div>
                                </div>


                              

                            </div>
                        </div>
                    </div>
                </div>


            <?php endif ?>




        <?php endforeach ?>

        <?php echo $requests->links();?>
    </div>
</div>


